# Generated by Django 5.0.14 on 2025-08-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction_manager", "0003_product_description_alter_product_name"),
        ("global_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_construction_manager.company",
            ),
        ),
    ]
