/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CustomDataTable: typeof import('./components/DataTable/CustomDataTable.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatingConfigurator: typeof import('./components/FloatingConfigurator.vue')['default']
    FooterDynamicDialog: typeof import('./components/DataTable/FooterDynamicDialog.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
