# Generated by Django 5.0.14 on 2025-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_construction_manager", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
